M48
; DRILL file {KiCad (6.0.8)} date Tue 08 Nov 2022 21:59:54 GMT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-08T21:59:54+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X198.355Y-86.75
X198.355Y-89.75
T2
X146.0Y-114.55
X179.7Y-109.1
T0
M30
